### ISSUE TITLE
What's up with the combination of JSON and XML?

### ISSUE THREAD

**Issue by ghost** [open-data/hnap#2]
This can probably all be done with JSON, I would assume?

**Comment by wardi** [comment]
This repo is my hand conversion of the example exported XML to json for submitting to ckan.

**Comment by chrismajewski** [comment]
I've presently got an HNAP XPATH extractor for Ross to pull from the FGP-CSW.  The CSW will provide the XML.

When Alannah and I are done mucking around with it I'll push it here.

**Comment by wardi** [comment]
@chrismajewski great. You should have commit access now
